version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      dotnet: 6.0
  pre_build:
    on-failure: ABORT
    commands:
    - echo Build start on 'date'
    - dotnet restore
    - echo Build ends on 'date'
  build:
    on-failure: ABORT
    commands:
    - echo Build start on 'date'
    - dotnet build
    - dotnet test
    - echo Build ends on 'date'
  post_build:
    on-failure: ABORT
    commands:
    - echo Build start on 'date'
    - dotnet publish
    - echo Build ends on 'date'

artifacts:
  files:
    - helloworld.dll
  name: hello-world-artifact
